apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
      #traefik.ingress.kubernetes.io/router.middlewares: 'kube-system-strip-path-prefix@kubernetescrd,kube-system-readarr-x-forwarded-prefix@kubernetescrd'
spec:
  ingressClassName: traefik
  rules:
    - host: media.picklemustard.dev
      http:
        paths:
          - path: /docs/tv
            pathType: Prefix
            backend:
              service:
                name: sonarr-service
                port:
                  number: 8989
