apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: auth-tcp
  namespace: lldap
  labels:
    app.kubernetes.io/name: auth-tcp
    app.kubernetes.io/instance: authelia
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: auth
    spec.ingressClassName: traefik
spec:
  entryPoints:
    - auth
  routes:
  - match: "HostSNI(`auth.picklemustard.dev`)"
    services:
      - name: authelia
        port: 9091
        nativeLB: true

