apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-headers-authelia
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
spec:
  
