apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-config
  namespace: collab
  labels:
    app.kubernetes.io/instance: openproject-config
    app.kubernetes.io/name: openproject-config
data:
  OPENPROJECT_HOST__NAME: "andromeda.picklemustard.dev"
  OPENPROJECT_HTTPS: "false"
  OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "/collab/plan"
  OPENPROJECT_DEFAULT__LANGUAGE: "en"
  OPENPROJECT__LDAP__HOST: "lldap-service.auth.svc.cluster.local"
  OPENPROJECT__LDAP__PORT: "3890"
  OPENPROJECT__LDAP__BASE: "dc=andromeda,dc=picklemustard,dc=dev"
  OPENPROJECT__LDAP__BIND__DN: "uid=bind_reader,ou=people,dc=andromeda,dc=picklemustard,dc=dev"
  OPENPROJECT__LDAP__ATTRIBUTE__LOGIN: "uid"
  OPENPROJECT__LDAP__ATTRIBUTE__FIRSTNAME: "cn"
  OPENPROJECT__LDAP__ATTRIBUTE__LASTNAME: "cn"
  OPENPROJECT__LDAP__ATTRIBUTE__EMAIL: "mail"
  OPENPROJECT__LDAP__VERIFY__PEER: "false"
  OPENPROJECT_SEED__ADMIN__USER__NAME: "endmin"
  OPENPROJECT_SEED__ADMIN__USER__PASSWORD: "purple14735#"
