apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-smb
  namespace: kube-system
data:
  driver.smb.csi.k8s.io: |-
    {
      "driverVersion": "v1.11.0",
      "apiVersion": "v1",
      "kind": "CSIDriver",
      "metadata": {
        "name": "smb.csi.k8s.io"
      },
      "spec": {
        "attachRequired": true,
        "podInfoOnMount": false
      }
    }
