apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stalwart-ingress
  namespace: stalwart
  labels:
    app.kubernetes.io/name: stalwart-ingress
    app.kubernetes.io/instance: stalwart
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: mail.picklemustard.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stalwart
                port:
                  number: 80
