apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingressroute
  namespace: auth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.picklemustard.dev`)
      kind: Rule
      priority: 100
      services:
        - name: vault-service
          port: 8200
