apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-tcp-ingress
  namespace: postgres 
  labels:
    app.kubernetes.io/name: postgres-tcp-ingress
    app.kubernetes.io/instance: postgres 
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: postgres
    spec.ingressClassName: traefik
spec:
  entryPoints:
    - postgres
  routes:
  - match: "HostSNI(`*`)"
    services:
      - name: postgres-postgresql
        port: 5432
        nativeLB: true
